title: builderscon::blog
description: > 
  builderscon is a festival for the technology lovers.
url: http://blog.builderscon.io
mainurl: http://builderscon.io
twitter_username: builderscon
github_username:  builderscon
fb_app_id: 537973726511652
fb_page_id: 1233910219973110

markdown: kramdown

authors:
  lestrrat:
    display_name: Daisuke Maki
    twitter: lestrrat 
    github: lestrrat
    web: http://lestrrat.github.io
    gravatar_id: f34e1745f7f8286586e921f7830eca78